# Generated by Django 5.0.6 on 2025-10-05 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0003_alter_historiquecirculationdocument_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquecirculationdocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historiquecirculationdocument',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
