# Generated by Django 5.0.6 on 2025-10-28 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='niveau_acces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.niveauaccesdocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='sous_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.soustypedocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.theme'),
        ),
        migrations.AddField(
            model_name='soustypedocument',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_types', to='documents.typedocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='type_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.typedocument'),
        ),
    ]
