# Generated by Django 5.0.6 on 2025-10-29 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='responsable_document',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_responsables', to=settings.AUTH_USER_MODEL),
        ),
    ]
