# Generated by Django 5.2.4 on 2025-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='document',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='niveauaccesdocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='niveauaccesdocument',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regleclassement',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regleclassement',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='soustypedocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='soustypedocument',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
