# Generated by Django 5.0.6 on 2025-10-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_modifier_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
