# Generated by Django 5.0.6 on 2025-10-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_cree_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='niveauaccesdocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='regleclassement',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soustypedocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
