# Generated by Django 5.0.6 on 2025-10-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_date_creation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regleclassement',
            old_name='description',
            new_name='description_regleclassement',
        ),
        migrations.AddField(
            model_name='niveauaccesdocument',
            name='description_niveauaccess',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soustypedocument',
            name='description_soustypedocument',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='description_theme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='description_typedocument',
            field=models.TextField(blank=True),
        ),
    ]
