# Generated by Django 5.0.6 on 2025-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveauaccesdocument',
            name='niveau',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='soustypedocument',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
