# Generated by Django 5.0.6 on 2025-10-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('documents', '0006_rename_description_regleclassement_description_regleclassement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='regles_classement',
        ),
        migrations.AlterField(
            model_name='document',
            name='cellule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.cellule'),
        ),
        migrations.DeleteModel(
            name='RegleClassement',
        ),
    ]
