# Generated by Django 5.0.6 on 2025-11-28 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_niveauaccesdocument_niveau_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True)),
                ('numero_version', models.PositiveIntegerField()),
                ('fichier', models.FileField(upload_to='documents/')),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_documents_crees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('modifier_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_documents_maj', to=settings.AUTH_USER_MODEL)),
                ('responsable_version', models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_documents_responsables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
