# Generated by Django 5.0.6 on 2025-12-01 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_cellule_nom_and_more'),
        ('documents', '0007_versiondocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bailleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrevation', models.CharField(max_length=255)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avenant_bailleur', to='documents.bailleurs')),
            ],
        ),
        migrations.CreateModel(
            name='Conventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True)),
                ('description_convention', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='conventions/')),
                ('etat', models.CharField(choices=[('attente', 'En attente'), ('traitement', 'En traitement'), ('valide', 'Validé'), ('archive', 'Archivé')], default='attente', max_length=20)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention_bailleur', to='documents.bailleurs')),
                ('cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.cellule')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_crees', to=settings.AUTH_USER_MODEL)),
                ('modifier_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_maj', to=settings.AUTH_USER_MODEL)),
                ('niveau_acces', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.niveauaccesdocument')),
                ('responsable_convention', models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_convention', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.theme')),
            ],
        ),
        migrations.CreateModel(
            name='AideMemoires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True)),
                ('description_aidememoires', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='aidememoires/')),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aidememoires_crees', to=settings.AUTH_USER_MODEL)),
                ('modifier_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aidememoires_maj', to=settings.AUTH_USER_MODEL)),
                ('responsable_aidememoire', models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_aidememoire', to=settings.AUTH_USER_MODEL)),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='documents.conventions')),
            ],
        ),
        migrations.CreateModel(
            name='Rapports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True)),
                ('description_rapports', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='rapports/')),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('aidememoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aidememoire', to='documents.aidememoires')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_crees', to=settings.AUTH_USER_MODEL)),
                ('modifier_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_maj', to=settings.AUTH_USER_MODEL)),
                ('responsable_rapport', models.ForeignKey(blank=True, limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_rapport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
