# Generated by Django 5.0.6 on 2025-12-01 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_cellule_nom_and_more'),
        ('documents', '0008_bailleurs_avenants_conventions_aidememoires_rapports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapports',
            name='aidememoire',
        ),
        migrations.RemoveField(
            model_name='conventions',
            name='bailleur',
        ),
        migrations.RemoveField(
            model_name='conventions',
            name='cellule',
        ),
        migrations.RemoveField(
            model_name='conventions',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='conventions',
            name='modifier_par',
        ),
        migrations.RemoveField(
            model_name='conventions',
            name='niveau_acces',
        ),
        migrations.RemoveField(
            model_name='conventions',
            name='responsable_convention',
        ),
        migrations.RemoveField(
            model_name='conventions',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='rapports',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='rapports',
            name='modifier_par',
        ),
        migrations.RemoveField(
            model_name='rapports',
            name='responsable_rapport',
        ),
        migrations.AddField(
            model_name='document',
            name='avenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_avenant', to='documents.avenants'),
        ),
        migrations.AddField(
            model_name='document',
            name='bailleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_bailleur', to='documents.bailleurs'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='documents.document'),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='cellule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.cellule'),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_types_fonctionnels', to='documents.typedocument'),
        ),
        migrations.DeleteModel(
            name='AideMemoires',
        ),
        migrations.DeleteModel(
            name='Conventions',
        ),
        migrations.DeleteModel(
            name='Rapports',
        ),
    ]
