# Generated by Django 5.0.6 on 2025-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_remove_rapports_aidememoire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenants',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='avenants',
            name='prenom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='abrevation',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bailleurs',
            name='libelle',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
