# Generated by Django 5.0.6 on 2025-12-03 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_cellule_accepte_bailleurs'),
        ('documents', '0010_alter_avenants_nom_alter_avenants_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailleurs',
            name='cellule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.cellule'),
        ),
    ]
