# Generated by Django 5.0.6 on 2025-12-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_bailleurs_cellule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='etat',
            field=models.CharField(choices=[('en attente', 'En Attente'), ('en traitement', 'En Traitement'), ('valide', 'Valide'), ('archive', 'Archive')], default='en attente', max_length=20),
        ),
    ]
