# Generated by Django 5.0.6 on 2026-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_documentpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpermission',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
    ]
