# Generated by Django 5.0.6 on 2026-03-18 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_documentpermission_can_download'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='permissions',
            field=models.ManyToManyField(related_name='documents_permissions', through='documents.DocumentPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_document_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
