# Generated by Django 5.0.6 on 2026-03-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_cellule_accepte_bailleurs'),
        ('documents', '0015_document_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='cellule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.cellule'),
        ),
    ]
