# Generated by Django 5.0.6 on 2026-03-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_theme_cellule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='niveau_acces',
            field=models.CharField(choices=[('public', 'Public'), ('interne', 'Interne'), ('restreint', 'Restreint'), ('confidentiel', 'Confidentiel'), ('secret', 'Secret')], default='interne', max_length=20),
        ),
    ]
