# Generated by Django 5.0.6 on 2026-04-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_document_niveau_acces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avenants',
            old_name='nom',
            new_name='libelle',
        ),
        migrations.RenameField(
            model_name='avenants',
            old_name='prenom',
            new_name='numero',
        ),
    ]
