# Generated by Django 5.0.6 on 2026-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_rename_nom_avenants_libelle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='etat',
            field=models.CharField(choices=[('en attente', 'En Attente'), ('en traitement', 'En Traitement'), ('validé', 'Valide'), ('archivé', 'Archive')], default='en attente', max_length=20),
        ),
    ]
