# Generated by Django 5.0.6 on 2026-05-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_document_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.theme'),
        ),
    ]
