# Generated by Django 5.0.6 on 2026-05-25 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20260525_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fichier',
        ),
    ]
