# Generated by Django 5.0.6 on 2026-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_division_statut'),
        ('documents', '0022_remove_document_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(fields=('libelle', 'cellule'), name='unique_libelle_cellule_theme'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('cellule__isnull', True)), fields=('libelle',), name='unique_libelle_generique_theme'),
        ),
        migrations.AddConstraint(
            model_name='typedocument',
            constraint=models.UniqueConstraint(fields=('libelle', 'cellule'), name='unique_libelle_cellule_typedoc'),
        ),
        migrations.AddConstraint(
            model_name='typedocument',
            constraint=models.UniqueConstraint(condition=models.Q(('cellule__isnull', True)), fields=('libelle',), name='unique_libelle_generique_typedoc'),
        ),
    ]
