# Generated by Django 5.0.6 on 2025-10-28 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationdocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
    ]
