# Generated by Django 5.0.6 on 2025-10-28 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circulation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationdocument',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='circulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
