# Generated by Django 5.0.6 on 2026-04-06 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_initial'),
        ('documents', '0017_alter_document_niveau_acces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circulationdocument',
            options={'ordering': ['-Date_creation']},
        ),
        migrations.RemoveField(
            model_name='circulationdocument',
            name='utilisateurs',
        ),
        migrations.AddField(
            model_name='circulationdocument',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circulationdocument',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='circulationdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='circulationdocument',
            name='initie_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulations_initiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circulationdocument',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('retourne', 'Retourné'), ('clos', 'Clos')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='circulationdocument',
            name='titre',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circulationdocument',
            name='date_debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='circulationdocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulations', to='documents.document'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('telechargement', 'Téléchargement'), ('impression', 'Impression'), ('circulation', 'Circulation'), ('tache', 'Tâche'), ('connexion', 'Connexion'), ('consultation', 'Consultation')], max_length=30)),
                ('objet_type', models.CharField(max_length=100)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objet_label', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('en_revision', 'En révision'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_faire', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('assignee_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_taches', to=settings.AUTH_USER_MODEL)),
                ('assignee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_assignees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='documents.document')),
            ],
            options={
                'ordering': ['-Date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(blank=True, max_length=20)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='circulation.tache')),
            ],
            options={
                'ordering': ['Date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapeCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('retourne', 'Retourné'), ('clos', 'Clos')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('Date_creation', models.DateTimeField(auto_now_add=True)),
                ('Date_miseajour', models.DateTimeField(auto_now=True)),
                ('circulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='circulation.circulationdocument')),
                ('destinataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_recues', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('circulation', 'ordre')},
            },
        ),
    ]
