# Generated by Django 5.0.6 on 2025-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulationdocument',
            name='utilisateurs',
            field=models.ManyToManyField(related_name='circulations', to='users.utilisateur'),
        ),
    ]
