# Generated by Django 5.0.6 on 2026-04-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_alter_circulationdocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='Date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
