# Generated by Django 5.0.6 on 2026-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0005_alter_auditlog_date_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['-priorite', '-Date_creation']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
