# Generated by Django 5.0.6 on 2026-04-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0006_alter_tache_options_alter_auditlog_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecirculation',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapecirculation',
            name='est_actuelle',
            field=models.BooleanField(default=False),
        ),
    ]
