# Generated by Django 5.0.6 on 2026-05-09 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0007_etapecirculation_date_reception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecirculation',
            name='date_echeance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='etapecirculation',
            name='titre_etape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
