# Generated by Django 5.0.6 on 2026-05-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0008_etapecirculation_date_echeance_and_more'),
        ('documents', '0019_alter_document_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecirculation',
            name='version_produite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etape_origine', to='documents.versiondocument'),
        ),
    ]
