# Generated by Django 5.0.6 on 2026-05-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0009_etapecirculation_version_produite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapecirculation',
            name='circulation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='circulation.circulationdocument'),
        ),
    ]
