# Generated by Django 5.0.6 on 2026-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0010_alter_etapecirculation_circulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecirculation',
            name='is_document_modifie',
            field=models.BooleanField(default=False),
        ),
    ]
