# Generated by Django 5.0.6 on 2026-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0011_etapecirculation_is_document_modifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_premiere_consultation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='nb_consultations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='titre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
