# Generated by Django 5.0.6 on 2026-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0012_tache_date_premiere_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulationdocument',
            name='date_premiere_consultation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circulationdocument',
            name='nb_consultations',
            field=models.IntegerField(default=0),
        ),
    ]
