# Generated by Django 5.0.6 on 2026-05-26 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0013_circulationdocument_date_premiere_consultation_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': "Journal d'audit", 'verbose_name_plural': "Journaux d'audit"},
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='objet_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='Date_creation',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='objet_type',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='statut',
            field=models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec')], db_index=True, default='success', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('telechargement', 'Téléchargement'), ('impression', 'Impression'), ('circulation', 'Circulation'), ('tache', 'Tâche'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, help_text='Stocke les deltas (avant/après) ou des précisions textuelles.', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='objet_label',
            field=models.CharField(blank=True, help_text="Nom/Titre de l'objet au moment de l'action", max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='circulation_content_72d63d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'action'], name='circulation_timesta_eb886d_idx'),
        ),
    ]
