# Generated by Django 5.0.6 on 2026-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0014_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('telechargement', 'Téléchargement'), ('impression', 'Impression'), ('circulation', 'Circulation'), ('tache', 'Tâche'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('suppression_masse', 'Suppression de masse'), ('traitement', "Traitement d'une étape de circulation")], db_index=True, max_length=30),
        ),
    ]
