# Generated by Django 5.0.6 on 2026-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0015_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('en_revision', 'En révision'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('en retard', 'En retard')], default='a_faire', max_length=20),
        ),
    ]
