# Generated by Django 5.0.6 on 2026-01-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_utilisateur_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('administrateur', 'Administrateur'), ('superviseur', 'Superviseur'), ('agent', 'Agent'), ('gestionnaire', 'Gestionnaire'), ('responsable', 'Responsable')], default='agent', max_length=255),
        ),
    ]
