# Generated by Django 5.0.6 on 2025-10-05 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_groups_alter_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roleutilisateur',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleutilisateur',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
