# Generated by Django 5.0.6 on 2026-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('administrateur', 'Administrateur'), ('superviseur', 'Superviseur'), ('gestionnaire', 'Gestionnaire'), ('responsable', 'Responsable')], default='responsable', max_length=255),
        ),
    ]
