# Generated by Django 5.0.6 on 2026-04-24 18:58

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_utilisateur_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.users.models.user_avatar_path),
        ),
    ]
