# Generated by Django 5.0.6 on 2026-07-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_division_statut'),
        ('users', '0006_alter_utilisateur_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cellules_supervisees',
            field=models.ManyToManyField(blank=True, help_text='Cellules supervisées par cet utilisateur (si rôle Superviseur)', related_name='superviseurs', to='administration.cellule'),
        ),
    ]
