# Generated by Django 5.0.6 on 2025-10-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='description_cellule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='division',
            name='description_division',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ministere',
            name='description_ministere',
            field=models.TextField(blank=True),
        ),
    ]
