# Generated by Django 5.0.6 on 2025-10-28 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_cellule_description_cellule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellule',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='division',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ministere',
            name='Date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministere',
            name='Date_miseajour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
