# Generated by Django 5.0.6 on 2025-11-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_ministere_abrevation_ministere_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellule',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='directiongenerale',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ministere',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
