# Generated by Django 5.0.6 on 2025-11-02 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_cellule_nom_alter_directiongenerale_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directiongenerale',
            name='ministere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions_generales', to='administration.ministere'),
        ),
    ]
