# Generated by Django 5.0.6 on 2025-11-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_directiongenerale_ministere'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='statut',
            field=models.CharField(choices=[('activé', 'Activé'), ('desactivé', 'Desactivé')], default='desactivé', max_length=255),
        ),
    ]
