# Generated by Django 5.0.6 on 2025-11-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_division_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellule',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='cellule',
            constraint=models.UniqueConstraint(fields=('nom', 'division'), name='unique_nom_division_cellule'),
        ),
    ]
