# Generated by Django 5.0.6 on 2025-12-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_cellule_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='accepte_bailleurs',
            field=models.BooleanField(default=False),
        ),
    ]
