# Generated by Django 5.0.6 on 2025-12-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_cellule_accepte_bailleurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellule',
            name='accepte_bailleurs',
            field=models.BooleanField(default=False, help_text="Designe la possibilité pour une cellule d'être lié à un bailleur"),
        ),
    ]
