# Generated by Django 5.0.6 on 2025-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_cellule_accepte_bailleurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellule',
            name='accepte_bailleurs',
            field=models.BooleanField(default=False, help_text='Designe la possibilité pour une cellule de gérer des bailleurs.'),
        ),
    ]
