# Generated by Django 5.0.6 on 2026-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_alter_cellule_accepte_bailleurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='statut',
            field=models.BooleanField(default=False),
        ),
    ]
