# Generated by Django 5.0.6 on 2026-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_division_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='statut',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
